### ISSUE TITLE
Scrolls textarea to the top

### ISSUE THREAD

**Issue by dennispopel** [imankulov/asuggest#1]
If the text in textarea overflows (so that vertical scroller gets shown), using the arrow keys scrolls the textarea to the top, hiding the oveflown text. This is annoying if you are panning around the overflown text - ie if the scroll top should not be zero.

Great library by the way, we are planning to use it in our Ukrainian miniblogging service http://friendbuzz.net - keep up the good work!

We would really appreciate if this bug is fixed. A great thank you!

**Comment by dennispopel** [comment]
using 0.2 btw

**Comment by imankulov** [comment]
Thank you for your report. The bug is indeed reproduced in Firefox. I'll try to fix it as soon as possible.

**Comment by imankulov** [comment]
Fixed bug with scrolling in Firefox. Closed by 2467e26810972296350aaba9ed7b02d2f10b614b
