### ISSUE TITLE
IE8 does not work

### ISSUE THREAD

**Issue by dennispopel** [imankulov/asuggest#3]
Unfortunately, asuggest does not work in IE8, and, obviously in older versions. It just shows the first suggested value, does not cycle on tab or allow entering first filtering characters. In fact, it seems that the field selection is not working there.

**Comment by imankulov** [comment]
Unfortunately, it seems that at the beginning I chose wrong underlying library (jquery.fieldselection) which is rather buggy and isn't supported by the author anymore. 

I'm planning to rewrite my own asuggest with [a-tools](http://plugins.jquery.com/project/a-tools) behind, and therefore I hope the bug will be closed by the next week.

**Comment by imankulov** [comment]
Fixed work with IE browsers

The crucial change in code is in fact in the first comment line: asuggest now
requires "jquery.a-tools" instead of "jquery.fieldselection". Closed by a76f4fa928967413ab7dc6c0cfa6f6e29a3fdb69
